app/blueprints/web/__init__.py
from flask import Blueprint

web = Blueprint(
    "web",
    __name__,
    static_folder="static",
    template_folder="templates",
    static_url_path='/static/web',
    url_prefix="/"
)

from . import views

def init_app(app):
    app.register_blueprint(web)

app/blueprints/web/events/__init__.py
from flask import Blueprint

events = Blueprint(
    "events",
    __name__,
    static_folder="static",
    static_url_path='/static/web',
    url_prefix="/admin"
)

from . import views

def init_app(app):
    app.register_blueprint(events)

app/blueprints/web/events/views.py
from flask import render_template, redirect, url_for, request, current_app, flash
from ext.database import Database as DB
from ext.utils import return_months, return_image
from ext.config import Config
from flask_paginate import Pagination, get_page_parameter

from . import events

db = DB()
config = Config()


@events.get("/events")
def list():
    limit = int(config.ITENS_PER_PAGE)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    offset = (page*limit) - limit

    events_total = db.count_events()
    events = db.return_all_events(limit, offset)

    pagination = Pagination(page=page, page_per=limit, total=events_total)

    return render_template(
        "events/list.html",
        pagination=pagination,
        events=events
    )


@events.route("/events/new", methods=["GET", "POST"])
def new():
    months = return_months()
    if request.method == "POST":
        title = request.form['title']
        description = request.form['description']
        image = request.form['image']
        dates = request.form['dates']
        month = request.form['month']
        year = request.form['year']

        if not title or not description or not image or not dates or not month or not year:
            flash("Check form data!", "danger")
        else:
            try:
                data = {
                    "title": title,
                    "description": description,
                    "image": image,
                    "dates": dates,
                    "month": month,
                    "year": year
                }
                db.insert_event(data)
                return redirect(url_for("events.list"))
            except Exception as err:
                flash("Fail on save form data!", "danger")
                current_app.logger.error(err)

    return render_template(
        "events/new.html",
        months=months
    )


@events.route("/events/edit/<int:event_id>", methods=["GET", "POST"])
def edit(event_id):
    event = db.select_event(event_id)
    months = return_months()

    if request.method == "POST":
        title = request.form['title']
        description = request.form['description']
        image = request.form['image']
        dates = request.form['dates']
        month = request.form['month']
        year = request.form['year']

        if not title or not description or not image or not dates or not month or not year:
            flash("Check form data!", "danger")
        else:
            try:
                data = {
                    "title": title,
                    "description": description,
                    "image": image,
                    "dates": dates,
                    "month": month,
                    "year": year
                }
                db.update_event(data, event_id)
                return redirect(url_for("events.list"))
            except Exception as err:
                flash("Fail on save form data!", "danger")
                current_app.logger.error(err)

    return render_template(
        "events/edit.html",
        event=event,
        months=months
    )


@events.get("/events/delete/<int:event_id>")
def delete(event_id):
    try:
        db.remove_event(event_id)
    except Exception as err:
        flash("Fail to remove event", "danger")
        current_app.logger.error(err)

    return redirect(url_for("events.list"))

app/blueprints/web/notifications/__init__.py
from flask import Blueprint

notifications = Blueprint(
    "notifications",
    __name__,
    static_folder="static",
    static_url_path='/static/web',
    url_prefix="/admin"
)

from . import views

def init_app(app):
    app.register_blueprint(notifications)

app/blueprints/web/notifications/views.py
from flask import render_template, redirect, url_for, request, current_app, flash
from ext.database import Database as DB
from ext.config import Config
from flask_paginate import Pagination, get_page_parameter

from . import notifications

db = DB()
config = Config()


@notifications.get("/notifications")
def list():
    limit = int(config.ITENS_PER_PAGE)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    offset = (page*limit) - limit

    notifications_total = db.count_notifications()
    notifications = db.return_all_notifications(limit, offset)

    pagination = Pagination(page=page, page_per=limit, total=notifications_total)

    return render_template(
        "notifications/list.html",
        pagination=pagination,
        notifications=notifications
    )


@notifications.route("/notifications/new", methods=["GET", "POST"])
def new():
    if request.method == "POST":
        content = request.form['content']
        if not content:
            flash("Check form data!", "danger")
        else:
            try:
                db.insert_notifications_message(content)
                return redirect(url_for("notifications.list"))
            except Exception as err:
                flash("Fail on save form data!", "danger")
                current_app.logger.error(err)

    return render_template("notifications/new.html")


@notifications.route("/notifications/edit/<int:notification_id>", methods=["GET", "POST"])
def edit(notification_id):
    notification = db.select_notification_message(notification_id)[0]

    if request.method == "POST":
        content = request.form['content']
        if not content:
            flash("Check form data!", "danger")
        else:
            try:
                content = request.form.get('content')
                db.update_notification_message(content, notification_id)
                return redirect(url_for("notifications.list"))
            except Exception as err:
                flash("Fail on save form data!", "danger")
                current_app.logger.error(err)

    return render_template("notifications/edit.html", content=notification)

@notifications.get("/notifications/delete/<int:notification_id>")
def delete(notification_id):
    try:
        db.remove_notification(notification_id)
    except Exception as err:
        flash("Fail on save form data!", "danger")
        current_app.logger.error(err)

    return redirect(url_for("notifications.list"))

app/blueprints/web/users/__init__.py
from flask import Blueprint

users = Blueprint(
    "users",
    __name__,
    static_folder="static",
    static_url_path='/static/web',
    url_prefix="/admin"
)

from . import views

def init_app(app):
    app.register_blueprint(users)

app/blueprints/web/users/views.py
from flask import render_template, request
from ext.database import Database as DB
from ext.config import Config
from flask_paginate import Pagination, get_page_parameter

from . import users

db = DB()
config = Config()


@users.route("/users", methods=["GET"])
def list():
    limit = int(config.ITENS_PER_PAGE)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    offset = (page*limit) - limit

    users_total = db.count_users()
    users = db.return_all_users(limit, offset)

    pagination = Pagination(page=page, page_per=limit, total=users_total)

    return render_template(
        "users/list.html",
        pagination=pagination,
        users=users
    )

app/blueprints/web/views.py
from flask import render_template, redirect, url_for
from ext.database import Database as DB

db = DB()

from . import web


@web.get("/")
def index():
    return redirect(url_for("web.admin"))


@web.get("/admin")
def admin():
    statistics = db.get_bot_statistics()
    return render_template("home.html", statistics=statistics)

app/blueprints/web/templates/events/edit.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="container">
    <form method="POST" action="">
        <fieldset>
            <label for="title">Title</label>
            <input type="text" placeholder="Title" name="title" value="{{ event.title }}">
            <label for="description">Description</label>
            <textarea placeholder="Description" name="description">{{ event.description }}</textarea>
            <label for="image">Image</label>
            <select name="image">
                <option {% if event.image == 'astrocal01.jpg' %} selected {% endif %} value="astrocal01.jpg">astrocal01.jpg</option>
                <option {% if event.image == 'astrocal02.jpg' %} selected {% endif %} value="astrocal02.jpg">astrocal02.jpg</option>
                <option {% if event.image == 'astrocal03.jpg' %} selected {% endif %} value="astrocal03.jpg">astrocal03.jpg</option>
                <option {% if event.image == 'astrocal04.jpg' %} selected {% endif %} value="astrocal04.jpg">astrocal04.jpg</option>
                <option {% if event.image == 'astrocal05.jpg' %} selected {% endif %} value="astrocal05.jpg">astrocal05.jpg</option>
                <option {% if event.image == 'astrocal06.jpg' %} selected {% endif %} value="astrocal06.jpg">astrocal06.jpg</option>
                <option {% if event.image == 'astrocal07.jpg' %} selected {% endif %} value="astrocal07.jpg">astrocal07.jpg</option>
                <option {% if event.image == 'astrocal08.jpg' %} selected {% endif %} value="astrocal08.jpg">astrocal08.jpg</option>
                <option {% if event.image == 'astrocal09.jpg' %} selected {% endif %} value="astrocal09.jpg">astrocal09.jpg</option>
                <option {% if event.image == 'astrocal10.jpg' %} selected {% endif %} value="astrocal10.jpg">astrocal10.jpg</option>
                <option {% if event.image == 'astrocal11.jpg' %} selected {% endif %} value="astrocal11.jpg">astrocal11.jpg</option>
                <option {% if event.image == 'astrocal12.jpg' %} selected {% endif %} value="astrocal12.jpg">astrocal12.jpg</option>
                <option {% if event.image == 'astrocal13.png' %} selected {% endif %} value="astrocal13.png">astrocal13.png</option>
                <option {% if event.image == 'astrocal14.jpg' %} selected {% endif %} value="astrocal14.jpg">astrocal14.jpg</option>
                <option {% if event.image == 'astrocal15.jpg' %} selected {% endif %} value="astrocal15.jpg">astrocal15.jpg</option>
                <option {% if event.image == 'astrocal16.jpg' %} selected {% endif %} value="astrocal16.jpg">astrocal16.jpg</option>
            </select>
            <label for="dates">Dates</label>
            <input type="text" placeholder="1,2" name="dates" value="{{ event.dates | join(',') }}">
            <label for="month">Month</label>
            <select name="month">
            {% for month in months %}
                <option {% if event.month == month['number'] %} selected {% endif %} value="{{ month['number'] }}">{{ month['name'] }}</option>
            {% endfor %}
            </select>
            <label for="year">Year</label>
            <input type="text" placeholder="2023" name="year" value="{{ event.year }}">
            {% include "layout/flash.html" %}
            <div class="clearfix">
                <div class="float-left">
                    <a class="button button-outline" href="{{ url_for("events.list") }}">Back</a>
                </div>
                <div class="float-right">
                    <input class="button" type="submit" value="Save">
                </div>
            </div>
        </fieldset>
    </form>
</div>

{% endblock %}

app/blueprints/web/templates/events/list.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="container">
    <div class="clearfix">
        <h3 class="float-left">Events</h3>
        <div class="float-right">
            <a class="button button-primary" href="{{ url_for("events.new") }}">New</a>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Image</th>
                <th>Dates</th>
                <th>Month</th>
                <th>Year</th>
                <th>Actions</th>
        </thead>
        <tbody>
            {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td>{{ event.title }}</td>
                <td>{{ event.description | truncate(150) }}</td>
                <td>{{ event.image }}</td>
                <td>{{ event.dates | join(',') }}</td>
                <td>{{ event.month }}</td>
                <td>{{ event.year }}</td>
                <td>
                    <a href="{{ url_for("events.edit", event_id=event.id) }}">
                        <i class="lni lni-pencil-alt"></i>
                    </a> |
                    <a href="{{ url_for("events.delete", event_id=event.id) }}">
                        <i class="lni lni-trash-can"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ pagination.links }}
</div>
{% endblock %}

app/blueprints/web/templates/events/new.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="container">
    <form method="POST" action="{{ url_for("events.new")}}">
        <fieldset>
            <label for="title">Title</label>
            <input type="text" placeholder="Title" name="title">
            <label for="description">Description</label>
            <textarea placeholder="Description" name="description"></textarea>
            <label for="image">Image</label>
            <select id="image" name="image">
                <option value="astrocal01.jpg">astrocal01.jpg</option>
                <option value="astrocal02.jpg">astrocal02.jpg</option>
                <option value="astrocal03.jpg">astrocal03.jpg</option>
                <option value="astrocal04.jpg">astrocal04.jpg</option>
                <option value="astrocal05.jpg">astrocal05.jpg</option>
                <option value="astrocal06.jpg">astrocal06.jpg</option>
                <option value="astrocal07.jpg">astrocal07.jpg</option>
                <option value="astrocal08.jpg">astrocal08.jpg</option>
                <option value="astrocal09.jpg">astrocal09.jpg</option>
                <option value="astrocal10.jpg">astrocal10.jpg</option>
                <option value="astrocal11.jpg">astrocal11.jpg</option>
                <option value="astrocal12.jpg">astrocal12.jpg</option>
                <option value="astrocal13.png">astrocal13.png</option>
                <option value="astrocal14.jpg">astrocal14.jpg</option>
                <option value="astrocal15.jpg">astrocal15.jpg</option>
                <option value="astrocal16.jpg">astrocal16.jpg</option>
            </select>
            <label for="dates">Dates</label>
            <input type="text" placeholder="1,2" name="dates">
            <label for="month">Month</label>
            <select name="month">
            {% for month in months %}
                <option value="{{ month['number'] }}">{{ month["name"] }}</option>
            {% endfor %}
            </select>
            <label for="year">Year</label>
            <input type="text" placeholder="2023" name="year">
            {% include "layout/flash.html" %}
            <div class="clearfix">
                <div class="float-left">
                    <a class="button button-outline" href="{{ url_for("events.list") }}">Back</a>
                </div>
                <div class="float-right">
                    <input class="button" type="submit" value="Save">
                </div>
            </div>
        </fieldset>
    </form>
</div>

{% endblock %}

app/blueprints/web/templates/home.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container">
    <h1>Astronomical Events</h1>
    <div class="row">
        <div class="column">
            <h3>Events: {{ statistics.count_all_events }}</h3>
        </div>
        <div class="column">
            <h3>Users: {{ statistics.count_all_users }}</h3>
            <p>With notifications enabled: {{ statistics.count_users_with_notifications_enabled }}</p>
        </div>
        <div class="column">
            <h3>Commands Triggered: {{ statistics.count_all_commands }}</h3>
        </div>
    </div>
</div>
{% endblock %}

app/blueprints/web/templates/layout/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Astronomical Events</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('web.static', filename='images/apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('web.static', filename='images/favicon-96x96.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('web.static', filename='images/favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('web.static', filename='images/favicon-16x16.png') }}">
        <link rel="manifest" href="{{ url_for('web.static', filename='manifest.json') }}">
        <link rel="stylesheet" href="{{ url_for('web.static', filename='css/lineicons.css') }}">
        <link rel="stylesheet" href="{{ url_for('web.static', filename='css/normalize.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('web.static', filename='css/miligram.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('web.static', filename='css/custom.css') }}">
    </head>
    <body>
        {% include "layout/navbar.html" %}
        <div class="header">
            {% block content %}{% endblock %}
        </div>
        <!-- <script src="" async defer></script> -->
    </body>
</html>

app/blueprints/web/templates/layout/flash.html
{% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="messages {{ category }}">
                <small>{{ message }}</small>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/blueprints/web/templates/layout/navbar.html
<nav class="navigation">
    <section class="container">
        <a class="navigation-title" href="{{ url_for('web.index') }}">
            <div class="title">
                <img class="logo" src="{{ url_for('web.static', filename='images/aeb.png') }}" alt="Logo">
            </div>
        </a>
        <ul class="navigation-list float-right">
            <li class="navigation-item"><a class="navigation-link" href="{{ url_for('events.list') }}">Events</a></li>
            <li class="navigation-item"><a class="navigation-link" href="{{ url_for('users.list') }}">Users</a></li>
            <li class="navigation-item"><a class="navigation-link" href="{{ url_for('notifications.list') }}">Notifications</a></li>
        </ul>
    </section>
</nav>

app/blueprints/web/templates/notifications/edit.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="container">
    <form method="POST" action="">
        <fieldset>
            <label for="content">Content</label>
            <textarea placeholder="Write the message to be sended here..." name="content">{{ content }}</textarea>
            {% include "layout/flash.html" %}
            <div class="clearfix">
                <div class="float-left">
                    <a class="button button-outline" href="{{ url_for("notifications.list") }}">Back</a>
                </div>
                <div class="float-right">
                    <input class="button" type="submit" value="Save">
                </div>
            </div>
        </fieldset>
    </form>
</div>

{% endblock %}

app/blueprints/web/templates/notifications/list.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="container">
    <div class="clearfix">
        <h3 class="float-left">Notifications</h3>
        <div class="float-right">
            <a class="button button-primary" href="{{ url_for("notifications.new") }}">New</a>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Content</th>
                <th>Is Sended</th>
                <th>Sended At</th>
                <th>Created</th>
                <th>Updated</th>
                <th>Actions</th>
        </thead>
        <tbody>
            {% for notification in notifications %}
            <tr>
                <td>{{ notification.id }}</td>
                <td>{{ notification.content | truncate(150) }}</td>
                <td>{% if notification.is_sended is true %} Yes {% else %} No {% endif %}</td>
                <td>
                    {% if notification.sended_at is none %}
                        -
                    {% else %}
                        {{ notification.sended_at | format_datetime }}
                    {% endif %}
                </td>
                <td>{{ notification.created_at | format_datetime }}</td>
                <td>{{ notification.updated_at | format_datetime }}</td>
                <td>
                    <a href="{{ url_for("notifications.edit", notification_id=notification.id) }}">
                        <i class="lni lni-pencil-alt"></i>
                    </a> |
                    <a href="{{ url_for("notifications.delete", notification_id=notification.id) }}">
                        <i class="lni lni-trash-can"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ pagination.links}}
</div>
{% endblock %}

app/blueprints/web/templates/notifications/new.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="container">
    <form method="POST" action="{{ url_for("notifications.new")}}">
        <fieldset>
            <label for="content">Content</label>
            <textarea placeholder="Write the message to be sended here..." name="content"></textarea>
            {% include "layout/flash.html" %}
            <div class="clearfix">
                <div class="float-left">
                    <a class="button button-outline" href="{{ url_for("notifications.list") }}">Back</a>
                </div>
                <div class="float-right">
                    <input class="button" type="submit" value="Save">
                </div>
            </div>
        </fieldset>
    </form>
</div>

{% endblock %}

app/blueprints/web/templates/users/list.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="container">
    <h3>Users</h3>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Telegram Chat ID</th>
                <th>Username</th>
                <th>Firstname</th>
                <th>Receive Notifications</th>
                <th>Date</th>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.chat_id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.firstname }}</td>
                <td>{% if user.receive_notifications is true %} Yes {% else %} No {% endif %}</td>
                <td>{{ user.datetime | format_datetime }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ pagination.links }}
</div>
{% endblock %}